export const SITE_NAME = "Cosmetychka shop"
export const SITE_DESCRIPTION = "Generated by create next app"

export const SUCCESS_MESSAGE =
  "Дякуємо за замовлення. Найближчим часом наш спеціаліст зв'яжеться з вами, щоб уточнити усі деталі."
export const ERROR_MESSAGE = "Сталась помилка під час оформлення вашого замовлення. Спробуйте пізніше."
